spring:
  datasource:
    url: jdbc:mysql://localhost:3306/learning?useSSL=false&serverTimezone=UTC
    username: learning
    password: w?Kzv2y7
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create